### PR TITLE
Update Polygon API for new v2 endpoints (#17)

### PR DESCRIPTION
**Pull request by Petersoj**
This PR is for #17.
There is somewhat of a problem though. The following aggregate API response has two fields with a different case, that is, "T" and "t" in the "results" section:
```
{
  "ticker": "AAPL",
  "status": "OK",
  "adjusted": true,
  "queryCount": 55,
  "resultsCount": 2,
  "results": [
    {
      "T": "AAPL",
      "v": 31315282,
      "o": 102.87,
      "c": 103.74,
      "h": 103.82,
      "l": 102.65,
      "t": 1549314000000,
      "n": 4
    }
  ]
}
```
This now produces the error:
```
Execution failed for task ':alpaca-java:generateJsonSchema2Pojo'.
> trying to create the same field twice: t
```
It appears to be the [`makeLowerCamelCase()`](https://github.com/joelittlejohn/jsonschema2pojo/blob/master/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/NameHelper.java#L108) method in jsonSchema2Pojo which makes the first character in a field name lowercase regardless of `propertyWordDelimiters` being set to nothing (which is supposed to prevent alterations to JSON fields names when generating the JSON). This happens with all versions of the jsonschema2pojo gradle plugin too...
I'm thinking of opening a PR in jsonschema2pojo to fix this for single characters.
I was looking into just using JSON Schemas for that particular class, but that would get tedious after Polygon changes their API responses.
Any ideas @mainstringargs?

### CODE REVIEW

**Comment by Petersoj** [comment]
Opened a PR in jsonschema2pojo here: https://github.com/joelittlejohn/jsonschema2pojo/pull/1031

**Comment by mainstringargs** [comment]
I think I may have seen this previously in another scenario, but I can't remember exactly which file it effected.  I believe what I did was manually grab the 'ticker' and not include the 'T' in the example json file.  You can see some of the hackery here:  https://github.com/mainstringargs/alpaca-java/blob/fbbd3d111c113259431564d77961f75c15fcb61a/src/main/java/io/github/mainstringargs/polygon/rest/PolygonRequest.java in 'getResponseObject' method.  Hopefully they will fix the issue in the jsonschema2pojo library itself, that would be great.

**Comment by Petersoj** [comment]
@mainstringargs Yeah that's pretty annoying... I've finished my PR over there. Hopefully they merge soon because I don't want to do that hackery haha. I also want to keep the objects as exposed as possible for people who are interfacing with this library and the ask price, size, and exchange JSON keys are now just the upper case of the bid price, size, and exchange keys so there will be even more hackery...

**Comment by mainstringargs** [comment]
Hey -- any feedback from the jsonschema2pojo about rolling it in?

**Comment by Petersoj** [comment]
@mainstringargs nothing yet. Looks like I’ll have to just do the hack. I’ll also look into using JSON schemas instead of JSON sources and see if I can generate unique getters and setters that way. I’ll work on this tomorrow and start the Polygon Websockets PR this weekend.

**Comment by mainstringargs** [comment]
No rush, was more curious than anything

**Comment by Petersoj** [comment]
Looks like it might be a while before that PR gets merged. We'll just have to go the with the hack...

**Comment by Petersoj** [comment]
I'm going to close this PR and reopen a new one with the changes to master so that I can resolve the issue with getter/setter name conflicts by implemented the changes in #24.

**Pull request closed without merging**
